language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: eRrmJaNKofEpUa5W7I41iUDuGCl4wsK3lZPquJBB4WSZXolgqi0zA1cEeYhfNST+8yKIc6dI65RW+FbRB2V8Fv2lRzHrpzFGNSNzLo676Astb0QbA5oI8i8tss8wb3qzoYDSjZ/hfy7Jsbt1ZD3BfEYakSxk3KbBFtM6KDuxbMICu0jbk1uXKojSljYkkRNzbF8e2bmi8iz+YXctIOXg4J1KnmtuUMI8A3u5UaqimMJ0DbeCcPNXogwtr0P2nqYyXwFen2fqnkQzxcv0qZ2FscE03k6JAR60JA4haJbbtBOYE7qWmBOSyqaYwlJWxhUSsPGDbB+lI+WN7VMldWYZC+NkOsxH5ezf4DOzhvflRORfwvlUsoHuBQXJ4v/mj2WWPP1uCDhhYB7QPo6a6ruiekgb3KLtp49On26/2z3Wgers23k5tdLB3Jm4qUP4ZCKR9M9uv3Ofbdb+WAyR4HUXP0/eDP91xi8w1pwLgNEYtHr+k3oqjuxeU0P9WDi5l8zdTJpPDiCQyjiMv9KWfbpqD5Fh6rfoMGcu7CCaZ7EdP3Scm7WwsfH748Ag9bom8bUWL4bJIY4QeChmdg25OwUXa1sRfWG7cj3bL7LvkLF4ZICFgipsJgK4lBaVREyJJwkc/aKlgE5Vt/xOvBU3qoTJuFOu3qy9SmLqZmV5Hw4icfw=
  app: murmuring-castle-16562
  on:
    repo: kmkaiulam/Lunchery
